server:
  port: 8081

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: catdog
    password: catdog
  thymeleaf:
    cache: false
  # Naver smtp server 사용
  mail:
     host: smtp.naver.com #smtp 서버 주소
     port: 465 # 메일 인증서버 포트
     username:  #네이버 아이디
     password:  #네이버 비밀번호
     properties:
       mail:
         smtp:
           starttls:
             enable: true
           # required: true
           auth: true
           # connectiontimeout: 5000
           # timeout: 5000
           # writetimeout: 5000
           ssl:
             #trust: smtp.naver.com
             enable: true #반드시 필요 -> SSL 필요로 되어있으면

# spring data jpa 설정
jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  open-in-view: false
  show-sql: true
  hibernate:
    ddl-auto: update
    #create로 하면 프로그램 시작할 때마다 table 다시 만들어짐
    #update는 바뀔 때만 변경. 그 외엔 유지